// theme.h - Deskstation visual theme tokens (M2)
#pragma once
#include "lvgl.h"

// Colors (from docs/spec). Defined as functions because lv_color_t can be a
// runtime-built value depending on LV_COLOR_DEPTH; macros for these don't
// work cleanly across all LVGL build configs.
lv_color_t theme_bg(void);          // #0d0d10
lv_color_t theme_card(void);        // #16161a
lv_color_t theme_accent(void);      // #1d9e75
lv_color_t theme_text(void);        // #f0f0f0
lv_color_t theme_text_dim(void);    // #a0a0a0
lv_color_t theme_danger(void);      // #d9534f

// Font size aliases. Custom Montserrat-Medium subset generated by
// tools/fonts/gen.sh — ASCII + Polish (Latin Extended-A: ąĄćĆęĘłŁńŃóÓśŚźŹżŻ)
// + degree + bullet + the standard LVGL_SYMBOL_* glyph set from FontAwesome 5.
extern const lv_font_t lv_font_pl_14;
extern const lv_font_t lv_font_pl_16;
extern const lv_font_t lv_font_pl_20;
extern const lv_font_t lv_font_pl_28;
#define THEME_FONT_SMALL  (&lv_font_pl_14)
#define THEME_FONT_NORMAL (&lv_font_pl_16)
#define THEME_FONT_LARGE  (&lv_font_pl_20)
#define THEME_FONT_TITLE  (&lv_font_pl_28)

// Convenience: paint screen background, set default text color/font, zero padding.
void theme_apply_to_screen(lv_obj_t *scr);
